@startuml
allowmixing
top to bottom direction
skinparam shadowing false
skinparam linetype ortho
skinparam nodesep 55
skinparam ranksep 65

actor "Visiteur" as Visiteur

class "IU-fil d'actualite" as Vue <<boundary>> {
  - actualites : List<News>
  + afficher()
}

class "C-fil d'actualite" as Controleur <<control>> {
  + charger()
}

package "Modeles" {
  class "News" as News <<entity>> {
    - <b>idNews</b> : int
    - titre : String
    - description : String
    - categorie : String
    - pays : String
    - source : String
    - datePublication : Date
    - url : String
    --
    + select()
  }
}

Visiteur -right-> Vue
Vue -down-> Controleur
Controleur -down-> News

@enduml
