@startuml
allowmixing
top to bottom direction
skinparam shadowing false
skinparam linetype ortho
skinparam nodesep 55
skinparam ranksep 65

actor "Editeur" as Editeur

class UI_CreerRoom <<boundary>> {
  -roomTitre : String
  -description : String
  -category : String
  -coverImageURL : String
  -createLiveRoomButton : Button
  + remplirFormulaire()
  + cliquerCreerRoom()
}

class UI_Live <<boundary>> {
  -openRoomButton : Button
  + afficherSucces()
}

class RoomController <<control>> {
  + createLiveEvent()
  + verifier()
}

package "Modeles" {
class Room <<entity>> {
  - <b>id</b> : int
  - titre : String
  - description : String
  - categorie : String
  - dateCreation : Date
  + insert()
}
}

UI_CreerRoom -[hidden]down- UI_Live

UI_CreerRoom -[hidden]right- UI_Live

Editeur -right- UI_CreerRoom
Editeur -right- UI_Live
UI_CreerRoom -down- RoomController
UI_Live -down- RoomController
RoomController -down- Modeles

@enduml
