@startuml

actor "utilisateur" as Utilisateur

participant ":UI s'abonner" as UISabonner
participant ":C s'abonner" as CSabonner
participant ":Utilisateur" as UtilisateurEntity


Utilisateur -> UISabonner : 1: saisir(information de payment)
Utilisateur -> UISabonner : 2: click_button_payment()

UISabonner -> CSabonner : 3: verifier()

alt payment valide
    CSabonner -> UtilisateurEntity : 4: update()
    CSabonner -> UISabonner : 5: afficher(payment valide)
else payment invalide
    CSabonner -> UISabonner : 6: afficher(payment invalide)
end

@enduml