@startuml
allowmixing
left to right direction

actor "utilisateur" as Utilisateur
' =========================
' Vue
' =========================
class IU_CommenterActualite <<View>> {
    -commentaire : String
    -boutton_post_commentaire : Button
    +saisir_commentaire()
    +click_bouton_post_commentaire()
    +afficher(message : String)
}

' =========================
' Contrôleur
' =========================
class C_CommenterActualite <<Controller>> {
    +ajouter()
}

' =========================
' Modèles
' =========================
package "Modeles" {
class News <<entity>> {
    - idActualite : int
    - titre : String
    - description : String
    - categorie : String
    - pays : String
    - source : String
    - datePublication : Date
    - url : String
    +update()
}

class Commentaire <<entity>> {
    -id : int
    -contenu : String
    -dateCommentaire : Date
    +insert()
}
}

' =========================
' Relations MVC
' =========================
Utilisateur -- IU_CommenterActualite
IU_CommenterActualite -- C_CommenterActualite
C_CommenterActualite -- Modeles
News -- Commentaire : association


@enduml