@startuml
allowmixing
left to right direction

actor "Visiteur" as Visiteur

class UI_SignUp <<boundary>> {
  -FullName : String
  -Email : String
  -Password : String
  -ConfirmPassword : String
  --
  + saisir(email,password,confirm-password)
  + clickBtnContinue()
  + afficher(message : String)

}

class UI_Interest <<boundary>> {
  -interests : List<String>
  -boutton_complete : Button
  --
  + choisirInterest()
  + clickBtnComplete()
}

class SignUpController <<control>> {
  + verifier()
}
package "Modeles" {
class Compte <<entity>> {
  - id : int
  - dateCreation : Date
  + select()
  + insert()
}

class Profile <<entity>> {
  - id : int
  - email : String
  - password : String
  + insert()
  + select()
}

class Interest <<entity>> {
  - id : int
  - nom : String
  + insert()
}
}
Visiteur -- UI_SignUp
Visiteur -- UI_Interest

UI_SignUp -- SignUpController
UI_Interest -- SignUpController

SignUpController -- Modeles

Profile -- Compte 
Interest -- Compte 
@enduml