@startuml
allowmixing
left to right direction
actor "Éditeur" as Editeur

class UI_CreerRoom <<boundary>> {
  -roomTitre : String
  -description : String
  -category : String
  -coverImageURL : String
  -createLiveRoomButton : Button
  + remplirFormulaire()
  + cliquerCreerRoom()
}
class UI_Live <<boundary>> {
  -openRoomButton : Button
  + afficherSuccès()
}

class RoomController <<control>> {
  + createLiveEvent()
  + verifier()
}
package "Modeles" {
class Room <<entity>> {
  - id : int
  - titre : String
  - description : String
  - categorie : String
  - dateCreation : Date
  + insert()
}

}
Editeur -- UI_CreerRoom
UI_CreerRoom -- RoomController
RoomController -- Modeles
UI_Live -- RoomController

@enduml