@startuml
allowmixing
left to right direction

actor "Utilisateur" as Utilisateur

class "IU-enregistrerActualité" as IU <<boundary>> {
  + clickBtnEnregistrerActualite()
  + afficher(message : String)
}

class "C-enregistrerActualité" as Controleur <<control>> {
  + verifier()
}

package "Modeles" as Modeles {
  together {
    class "Favorite" as Favorite <<entity>> {
      - idFavorite : int
      - idUtilisateur : int
      - idNews : int
      --
      + select()
      + insert()
      + delete()
    }
  }
}
Utilisateur -- IU
IU -- Controleur
Controleur -- Modeles

@enduml