@startuml
allowmixing
top to bottom direction
skinparam shadowing false
skinparam linetype ortho
skinparam nodesep 55
skinparam ranksep 65

actor "Utilisateur" as Utilisateur

class "IU-enregistrerActualite" as IU <<boundary>> {
  + clickBtnEnregistrerActualite()
  + afficher(message : String)
}

class "C-enregistrerActualite" as Controleur <<control>> {
  + verifier()
}

package "Modeles" as Modeles {
  class "Favorite" as Favorite <<entity>> {
    - <b>idFavorite</b> : int
    - dateAjout : Date
    --
    + select()
    + insert()
    + delete()
  }
}

Utilisateur -right- IU
IU -down- Controleur
Controleur -down- Modeles

@enduml
