@startuml
allowmixing
left to right direction

actor "Visiteur" as Visiteur

class IUFiltrerActualite <<boundary>> {
  - boutonsCategorie : List<Button>
  - champPays : String
  - champSource : String
  - champType : String
  - champDate : Date
  --
  + afficher(filtres)
  + choisir(filtres)
  + afficher(actualite)
}

class CFiltrerActualite <<control>> {
  + charger(filtres)
  + charger(actualite)
  + verifier(filtres)
}

class News <<entity>> {
  - idNews : int
  - titre : String
  - description : String
  - categorie : String
  - pays : String
  - source : String
  - datePublication : Date
  - url : String
  --
  + select()
}

Visiteur -- IUFiltrerActualite
IUFiltrerActualite -- CFiltrerActualite
CFiltrerActualite -- News

@enduml