@startuml
allowmixing
left to right direction

actor Visiteur

class IULogin <<boundary>> {
  - email : String
  - password : String
  - buttonSignIn : Button
  + saisir(email, password)
  + clickBtnSignIn()
  + afficher()
}

class CLogin <<control>> {
  + chercher()
}

package model {
  class Profile <<entity>> {
    - id : int
    - email : String
    - password : String
    + select()
  }
}

Visiteur -- IULogin
IULogin -- CLogin
CLogin -up- model

@enduml